# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e1b1b54f0368993b70236efd70d8fd413113857d870283c861d96ca3d72e29d1d9675eeea9b9e83f2f994f7cf7bd7262a779666b36cf45059570ecb7990d1cd

test:
  secret_key_base: 1e335b3a8e1ce794af965f7a191d019719121d498d4c87a374260f58b27e6cd6f43ec587ddda0ccc1b09601b4db7e5af4658362526c3a228a1e2f3690f14e7e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
